name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: bewerbung

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build --configuration Release
      
      - name: Docker Build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: docker build . -t ${{ env.DOCKER_IMAGE }}:test

      - name: Docker Tag and Push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          FULL_TAG="${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest"
          
          docker tag "${{ env.DOCKER_IMAGE }}:test" "$FULL_TAG"
          
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
          docker push "$FULL_TAG"